---
- hosts: all
  become: yes
  vars_files:
    - vars.yml

  tasks:

  - name: Generate a list we will iterate over
    set_fact:
      iterations: "{{ item | list }}"
    with_sequence: start=1 end="{{ max_iterations }}"
    run_once: yes

  - name: Run main tasks file
    include_tasks: tasks.yml
    loop:
      #- "{{ iterations }}"
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
    loop_control:
      loop_var: current_iteration
