---
- hosts: all
  become: yes
  vars_files:
    - vars.yml

  tasks:

  - name: Generate a list we will iterate over
    set_fact:
      restart_iterations: "{{ restart_iterations | default([]) + [item | int] }}"
    with_sequence: start=1 end="{{ max_iterations }}"
    run_once: yes

  - debug:
      var: restart_iterations

  - name: Run main tasks file
    include_tasks: tasks.yml
    loop:  "{{ restart_iterations }}"
    loop_control:
      loop_var: current_iteration
